### ISSUE TITLE
SLF4J hangs

### ISSUE THREAD

**Issue by plasne** [Azure/azure-functions-java-worker#53]
If creating the sample from here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-java-maven 

When adding this to the pom.xml:

```bash
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>1.7.25</version>
</dependency>
```

Adding this to the Function.java file:

```bash
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
```

And adding this to the HttpResponseMessage function:

```bash
Logger logger = LoggerFactory.getLogger(Function.class);
```

The function will hang on the getLogger call. Given the popularity of SLF4J, it would be great to either fix this or document that it doesn't work so time is not waited thinking something else is wrong.

**Comment by JonathanGiles** [comment]
I suspect this is the same issue as https://github.com/Azure/azure-functions-java-worker/issues/46, for which a resolution is forthcoming: https://github.com/Azure/azure-functions-java-worker/pull/50

**Comment by kevinhillinger** [comment]
+ @JunyiYi 

@plasne It is the issue. I've verified this, and put a sample with instructions [here](https://github.com/kevinhillinger/azure-functions-samples/tree/master/azure-functions-slf4j) to temporarily pull down `dev` branch, build, and run with the latest worker.

The sample also has the correct POM plugins to properly support deploying the dependencies into the azure functions' lib directory, where they will get picked up.

/cc @JonathanGiles

**Comment by kevinhillinger** [comment]
As this is resolved in the current codebase, recommending the issue be closed.

**Comment by JunyiYi** [comment]
The bug is fixed in the latest code base. And let me close the issue after it is published to Azure.

**Comment by plasne** [comment]
@kevinhillinger If I pull down the latest dev branch it builds to beta3, and that has a number of issues. If I git checkout tags/1.0.0-beta-2 and then build, I have the beta2 file you specified. I can replace that as the worker and when it starts up it is pointing to that correct file in the logs. However, it will still hang if I do:

```bash
Logger logger = LoggerFactory.getLogger(Function.class);
```

...removing that line lets it operate as normal. Is it possible what got tagged as beta-2 is an earlier/later build than you tested?

**Comment by kevinhillinger** [comment]
@plasne can you confirm again? [Here's a sample that does work find for me](https://github.com/kevinhillinger/azure-functions-samples/tree/master/java/slf4j). Azure has been updated with the latest preview bits.

**Comment by plasne** [comment]
I have confirmed that it works. I think the issue was probably that I didn't have the POM changes to include deploying to the lib folder. If you don't have that, it just hangs forever with no explanation.

Is there a preference for the lib folder over shade? Does only one work? Or are either appropriate?

**Comment by JonathanGiles** [comment]
Peter, the advice moving forward is to not use shade and only use the lib folder approach. Soon the shade advice will no longer be given.

**Comment by JunyiYi** [comment]
Thanks @plasne for the confirmation.
